### ISSUE TITLE
vuepress-plugin-global-toc

### ISSUE THREAD

**Issue by sylvainpolletvillard** [ulivz/awesome-vuepress#47]
Hello,

I released my first vuepress plugin, and am looking for feedback. I saw that @ulivz you got some experience on the matter :)

https://github.com/sylvainpolletvillard/vuepress-plugin-global-toc

It is a very simple plugin that adds a GlobalTableOfContents component, to be used as an alternative for `[[toc]]` but that covers the entire vuepress website. I had this specific need for two documentation websites and did not find an existing solution, so I wrote one.

If you like it and feel it is worth it, I would be glad to add this to the list of community plugins here.

**Comment by ulivz** [comment]
Feel free to submit pull request :)

**Comment by sylvainpolletvillard** [comment]
done, closing this issue
